=== Micro-PHP/dto/src/Resource/schema/dto-1.6.xsd
<xs:schema elementFormDefault="qualified" targetNamespace="micro:dto-1.6" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dto"  type="mic:dtoType" xmlns:mic="micro:dto-1.6"/>

    <xs:complexType name="dtoType">
        <xs:sequence>
            <xs:element type="mic:classType" name="class" maxOccurs="unbounded" xmlns:mic="micro:dto-1.6"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="classType">
        <xs:sequence>
            <xs:element type="mic:propertyType" name="property" maxOccurs="unbounded" minOccurs="0" xmlns:mic="micro:dto-1.6"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="description"/>
        <xs:attribute type="xs:string" name="deprecated"/>
    </xs:complexType>
    <xs:complexType name="propertyType" mixed="true">
        <xs:sequence>
            <xs:element type="mic:validationType" name="validation" minOccurs="0" xmlns:mic="micro:dto-1.6"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="type"/>
        <xs:attribute type="xs:string" name="description"/>
        <xs:attribute type="xs:string" name="deprecated"/>
        <xs:attribute type="xs:boolean" name="is_collection"/>
        <xs:attribute type="xs:boolean" name="required"/>
    </xs:complexType>
    <!-- Validation nodes -->
    <xs:complexType name="validationType">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="is_null" type="mic:constraint_is_null" xmlns:mic="micro:dto-1.6"/>
                <xs:element name="blank" type="mic:constraint_blank" xmlns:mic="micro:dto-1.6"/>
                <xs:element name="not_blank" type="mic:constraint_not_blank" xmlns:mic="micro:dto-1.6"/>
                <xs:element name="email" type="mic:constraint_email" xmlns:mic="micro:dto-1.6"/>
                <xs:element name="ip" type="mic:constraint_ip" xmlns:mic="micro:dto-1.6"/>
                <xs:element name="hostname" type="mic:constraint_hostname" xmlns:mic="micro:dto-1.6"/>
                <xs:element name="url" type="mic:constraint_url" xmlns:mic="micro:dto-1.6"/>
                <xs:element name="regex" type="mic:constraint_regex" xmlns:mic="micro:dto-1.6"/>
                <xs:element name="length" type="mic:constraint_size" xmlns:mic="micro:dto-1.6"/>
                <xs:element name="json" type="mic:constraint_json" xmlns:mic="micro:dto-1.6"/>
                <xs:element name="uuid" type="mic:constraint_uuid" xmlns:mic="micro:dto-1.6"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <!-- End validation nodes -->
    <!-- Constraints types -->
    <xs:complexType name="constraint_email" xml:base="dtoType">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract" xmlns:mic="micro:dto-1.6">
                <xs:attribute name="mode" default="html5">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="html5" />
                            <xs:enumeration value="html5-allow-no-tld" />
                            <xs:enumeration value="strict" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_ip">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract" xmlns:mic="micro:dto-1.6">
                <xs:attribute name="version" default="4">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="4" />
                            <xs:enumeration value="6" />
                            <xs:enumeration value="all" />
                            <xs:enumeration value="4_no_priv"/>
                            <xs:enumeration value="6_no_priv" />
                            <xs:enumeration value="all_no_priv"/>
                            <xs:enumeration value="all_no_priv"/>
                            <xs:enumeration value="4_no_res"/>
                            <xs:enumeration value="6_no_res"/>
                            <xs:enumeration value="all_no_res"/>
                            <xs:enumeration value="4_public"/>
                            <xs:enumeration value="6_public"/>
                            <xs:enumeration value="all_public"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_hostname">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract" xmlns:mic="micro:dto-1.6">
                <xs:attribute name="ltd_required" type="xs:boolean" default="false" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_url">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract" xmlns:mic="micro:dto-1.6">
                <xs:attribute name="is_relative" type="xs:boolean" default="false" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_regex">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract" xmlns:mic="micro:dto-1.6">
                <xs:attribute type="xs:string" name="pattern" use="required" />
                <xs:attribute type="xs:boolean" name="match" default="true" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_size">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract_groups" xmlns:mic="micro:dto-1.6">
                <xs:attribute type="xs:int" name="min" use="required"/>
                <xs:attribute type="xs:int" name="max" use="required"/>
                <xs:attribute type="xs:string" name="message_min" />
                <xs:attribute type="xs:string" name="message_max"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_blank">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract" xmlns:mic="micro:dto-1.6"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_not_blank">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract" xmlns:mic="micro:dto-1.6">
                <xs:attribute name="allow_null" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_is_null">
       <xs:complexContent>
           <xs:extension base="mic:constraint_abstract"  xmlns:mic="micro:dto-1.6"/>
       </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_json">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract"  xmlns:mic="micro:dto-1.6"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_uuid">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract"  xmlns:mic="micro:dto-1.6">
                <xs:attribute name="strict" default="true" />
                <xs:attribute name="versions" default="1,2,3,4,5,6,7" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_abstract">
        <xs:complexContent>
            <xs:extension base="mic:constraint_abstract_groups" xmlns:mic="micro:dto-1.6">
                <xs:attribute type="xs:string" name="message" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="constraint_abstract_groups">
        <xs:attribute type="xs:string" name="groups" default="Default" />
    </xs:complexType>
    <!-- Constraints types END -->
</xs:schema>

=== Micro-PHP/dto/example/example.xml
<?xml version="1.0"?>
<dto xmlns="micro:dto-1.6"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="micro:dto-1.6 ../src/Resource/schema/dto-1.6.xsd">

    <class name="Simple\SimpleObject">
        <property name="weight" type="int"/>
    </class>

    <class name="Simple\SimpleObject">
        <property name="height" type="int"/>
    </class>
    <class name="Simple\SimpleObject">
        <property name="parent" type="Simple\SimpleObject"/>
    </class>

    <class name="Simple\SimpleUser">
        <property name="parent" type="Simple\SimpleObject"/>
        <property name="username" type="string">
            <validation>
                <constraint group="test">
                    <length min="8" max="50"/>
                    <regex pattern="/^(.[aA-zA]+)$/"/>
                </constraint>
                <constraint>
                    <length min="8" max="10" message_min="invalid username"/>
                    <regex pattern="/^(.[aA-zA]+)$/"/>
                </constraint>
            </validation>
        </property>
        <property name="age" type="int">
            <validation>
                <constraint>
                    <blank/>
                </constraint>
            </validation>
        </property>
        <property name="email" type="string">
            <validation>
                <constraint>
                    <email/>
                    <not_blank/>
                </constraint>
            </validation>
        </property>
        <property name="ip" type="string">
            <validation>
                <constraint>
                    <ip/>
                </constraint>
            </validation>
        </property>
        <property name="hostname" type="string">
            <validation>
                <constraint>
                    <hostname/>
                </constraint>
                <constraint group="test">
                    <hostname ltd_required="true"/>
                </constraint>
            </validation>
        </property>
        <property name="sometext" type="string">
            <validation>
                <constraint>
                    <regex pattern="/^(.[a-z])+$/"/>
                </constraint>
            </validation>
        </property>
        <property name="url" type="string">
            <validation>
                <constraint>
                    <url is_relative="true" />
                </constraint>
            </validation>
        </property>
        <property name="json" type="string">
            <validation>
                <constraint>
                    <not_blank/>
                    <json/>
                </constraint>
            </validation>
        </property>
        <property name="uuid" type="string">
            <validation>
                <constraint>
                    <not_blank />
                    <uuid />
                </constraint>
            </validation>
        </property>
    </class>

    <class name="User" description="Example class description" deprecated="Please, use gSON">
        <property name="username" type="string|int" description="Username" deprecated="Deprecation  message"/>
        <property name="books" type="array" is_collection="true"/>
        <property name="first_name" type="string|int" required="true"/>
        <property name="updatedAt" type="date"/>
        <property name="someclass" type="abstract"/>
        <property name="testMixed" type="mixed"/>
    </class>
</dto>
